version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build_and_test
