export default [
  "A Clockwork Orange (Movie)",
  "A Confederacy of Dunces (Book)",
  "A Scanner Darkly (Book)",
  "A Song of Ice and Fire (Book)",
  "A Tale of Two Cities (Book)",
  "A Wrinkle in Time (Book)",
  "Abarat (Book)",
  "Adventures of Huckleberry Finn, The (Book)",
  "Adventures of Sherlock Holmes, The (Book)",
  "Alanna: The First Adventure (Book)",
  "Alchemist, The (Book)",
  "American Gods (Book)",
  "Animal Farm (Book)",
  "Arrested Development (Series)",
  "Arrows of the Queen (Book)",
  "Atlas Shrugged (Book)",
  "Avatar (Movie)",
  "Battlestar Galactica (Series)",
  "Beloved (Book)",
  "Black Mirror (Series)",
  "Blade Runner (Movie)",
  "Blue Sword, The (Book)",
  "Book Thief, The (Book)",
  "Brave New World (Book)",
  "Breaking Bad (Series)",
  "Bridge to Terabithia (Book)",
  "Brief Wondrous Life of Oscar Wao, The (Book)",
  "Brothers Karamazov, The (Book)",
  "Buffy the Vampire Slayer (Series)",
  "Catch-22 (Book)",
  "Catcher in the Rye, The (Book)",
  "Chronicles of Narnia, The (Book)",
  "Chronicles of Prydain, The (Book)",
  "Chrono Cross (Video Game)",
  "Chrono Trigger (Video Game)",
  "City of Illusions (Book)",
  "Color Purple, The (Book)",
  "Colour of Magic, The (Book)",
  "Conan the Barbarian (Movie)",
  "Count of Monte Cristo, The (Book)",
  "Crime and Punishment (Book)",
  "Crying of Lot 49, The (Book)",
  "Curious Incident of the Dog in the Night-Time, The (Book)",
  "Da Vinci Code, The (Book)",
  "Dark Tower, The (Book)",
  "Dilbert (Comic Strip)",
  "Dinotopia (Book)",
  "Dispossessed, The (Book)",
  "Divine Comedy, The (Book)",
  "Doctor Who (Series)",
  "Don Quixote (Book)",
  "Doomsday Book (Book)",
  "Dracula (Book)",
  "Dragon Age: Origins (Video Game)",
  "Dragon Prince, The (Series)",
  "Dragonriders of Pern (Book)",
  "Dragons of Autumn Twilight (Book)",
  "Dune (Book)",
  "Dungeons & Dragons (Tabletop Game)",
  "East of Eden (Book)",
  "Elder Scrolls III: Morrowind, The (Video Game)",
  "Elder Scrolls IV: Oblivion, The (Video Game)",
  "Empire of the East (Book)",
  "Ender's Game (Book)",
  "Eragon (Book)",
  "Excalibur (Movie)",
  "Expanse, The (Series)",
  "Fahrenheit 451 (Book)",
  "Fargo (Movie)",
  "Fight Club (Movie)",
  "Firefly (Series)",
  "Fountainhead, The (Book)",
  "Frankenstein (Book)",
  "Friends (Series)",
  "Game of Thrones (Series)",
  "Girl with the Dragon Tattoo, The (Book)",
  "Giver, The (Book)",
  "God of Small Things, The (Book)",
  "Godfather, The (Movie)",
  "Gone Girl (Book)",
  "Good Omens (Book)",
  "Grapes of Wrath, The (Book)",
  "Gravity's Rainbow (Book)",
  "Great Expectations (Book)",
  "Great Gatsby, The (Book)",
  "Guards! Guards! (Book)",
  "Guild Wars (Video Game)",
  "Gulliver's Travels (Book)",
  "Gunslinger, The (Book)",
  "Handmaid's Tale, The (Book)",
  "Harry Potter and the Philosopher's Stone (Book)",
  "He-Man and the Masters of the Universe (Series)",
  "Heart of Darkness (Book)",
  "Hello from the Magic Tavern (Podcast)",
  "His Dark Materials (Book)",
  "Hitchhiker's Guide to the Galaxy, The (Book)",
  "Hound of the Baskervilles, The (Book)",
  "House of Leaves (Book)",
  "Howl's Moving Castle (Book)",
  "Hunger Games, The (Book)",
  "Iliad, The (Book)",
  "Inception (Movie)",
  "Infinite Jest (Book)",
  "Jane Eyre (Book)",
  "Jonathan Strange & Mr Norrell (Book)",
  "Jurassic Park (Movie)",
  "Kite Runner, The (Book)",
  "Last Herald-Mage, The (Book)",
  "Left Hand of Darkness, The (Book)",
  "Legend of Zelda, The (Video Game)",
  "Les Misérables (Book)",
  "Life of Pi (Book)",
  "Lion, the Witch and the Wardrobe, The (Book)",
  "Little Women (Book)",
  "Lonesome Dove (Book)",
  "Lord of the Flies (Book)",
  "Lord of the Rings, The (Book)",
  "Lost (Series)",
  "Lovely Bones, The (Book)",
  "Mad Men (Series)",
  "Magic Kingdom for Sale--Sold! (Book)",
  "Magic: The Gathering (Tabletop Game)",
  "Magicians, The (Book)",
  "Malazan Book of the Fallen, The (Book)",
  "Mass Effect (Video Game)",
  "Master and Margarita, The (Book)",
  "Matrix, The (Movie)",
  "Maus (Graphic Novel)",
  "Memoirs of a Geisha (Book)",
  "Mistborn: The Final Empire (Book)",
  "Moby-Dick (Book)",
  "Name of the Wind, The (Book)",
  "Neuromancer (Book)",
  "Neverwhere (Book)",
  "Night Circus, The (Book)",
  "Nine Princes in Amber (Book)",
  "Nineteen Eighty-Four (Book)",
  "Odyssey, The (Book)",
  "Of Mice and Men (Book)",
  "Office, The (Series)",
  "Old Man and the Sea, The (Book)",
  "One Flew Over the Cuckoo's Nest (Book)",
  "One Hundred Years of Solitude (Book)",
  "Outsiders, The (Book)",
  "Pathfinder (Tabletop Game)",
  "Perdido Street Station (Book)",
  "Peter Pan (Book)",
  "Picture of Dorian Gray, The (Book)",
  "Pillars of the Earth, The (Book)",
  "Planet of Exile (Book)",
  "Pride and Prejudice (Book)",
  "Princess Bride, The (Movie)",
  "Pulp Fiction (Movie)",
  "Ready Player One (Book)",
  "Red Dead Redemption (Video Game)",
  "Requiem for a Dream (Movie)",
  "Road, The (Book)",
  "Sandman, The (Graphic Novel)",
  "Scar, The (Book)",
  "Scarlet Letter, The (Book)",
  "Schindler's List (Movie)",
  "Secret Garden, The (Book)",
  "Secret Life of Bees, The (Book)",
  "Seinfeld (Series)",
  "Sense and Sensibility (Book)",
  "Shawshank Redemption, The (Movie)",
  "She-Ra and the Princesses of Power (Series)",
  "Shining, The (Book)",
  "Silmarillion, The (Book)",
  "Simpsons, The (Series)",
  "Slaughterhouse-Five (Book)",
  "Sopranos, The (Series)",
  "Sound and the Fury, The (Book)",
  "Stand, The (Book)",
  "Star Trek (Series)",
  "Star Wars (Movie)",
  "Stranger Things (Series)",
  "Three Musketeers, The (Book)",
  "Time Traveler's Wife, The (Book)",
  "Tinker, Tailor, Soldier, Spy (Book)",
  "To Kill a Kingdom (Book)",
  "To Kill a Mockingbird (Book)",
  "Treasure Island (Book)",
  "Trial, The (Book)",
  "Twin Peaks (Series)",
  "Ulysses (Book)",
  "War and Peace (Book)",
  "War of the Worlds, The (Book)",
  "Warhammer 40,000 (Tabletop Game)",
  "Warhammer: Age of Sigmar (Tabletop Game)",
  "Warhammer Fantasy (Tabletop Game)",
  "Watchmen (Graphic Novel)",
  "Way of Kings, The (Book)",
  "Westworld (Series)",
  "Wheel of Time, The (Book)",
  "Wicked (Book)",
  "Wizard of Oz, The (Book)",
  "World of Warcraft (Video Game)",
  "Wuthering Heights (Book)",
  "X-Files, The (Series)",

  "Naruto (Anime)",
  "One Piece (Anime)",
  "Dragon Ball (Anime)",
  "Dragon Ball Z (Anime)",
  "Dragon Ball Super (Anime)",
  "Bleach (Anime)",
  "Attack on Titan (Anime)",
  "Fullmetal Alchemist (Anime)",
  "Death Note (Anime)",
  "Cowboy Bebop (Anime)",
  "My Hero Academia (Anime)",
  "Neon Genesis Evangelion (Anime)",
  "Sword Art Online (Anime)",
  "One Punch Man (Anime)",
  "Fairy Tail (Anime)",
  "Hunter x Hunter (Anime)",
  "Tokyo Ghoul (Anime)",
  "Gintama (Anime)",
  "JoJo's Bizarre Adventure (Anime)",
  "Code Geass (Anime)",
  "Nanatsu no Taizai (Anime)",
  "Berserk (Anime)",
  "Steins;Gate (Anime)",
  "Durarara!! (Anime)",
  "Black Clover (Anime)",
  "Demon Slayer (Anime)",
  "Gundam (Anime)",
  "Ghost in the Shell (Anime)",
  "Akira (Anime)",
  "Psycho-Pass (Anime)",
  "Your Lie in April (Anime)",
  "Clannad (Anime)",
  "K-On! (Anime)",
  "Re:Zero (Anime)",
  "Overlord (Anime)",
  "No Game No Life (Anime)",
  "Magi (Anime)",
  "Soul Eater (Anime)",
  "Trigun (Anime)",
  "Elfen Lied (Anime)",
  "Hellsing (Anime)",
  "Blue Exorcist (Anime)",
  "Violet Evergarden (Anime)",
  "Samurai Champloo (Anime)",
  "Kill la Kill (Anime)",
  "Toradora! (Anime)",
  "Made in Abyss (Anime)",
  "Puella Magi Madoka Magica (Anime)",
  "Angel Beats! (Anime)",
  "Ergo Proxy (Anime)",
  "Darker than Black (Anime)",
  "Spice and Wolf (Anime)",

  "12 Angry Men (Movie)",
  "2001: A Space Odyssey (Movie)",
  "A Beautiful Mind (Movie)",
  "A Christmas Carol (Book)",
  "A Streetcar Named Desire (Book)",
  "Alice's Adventures in Wonderland (Book)",
  "American Psycho (Book)",
  "Anansi Boys (Book)",
  "And Then There Were None (Book)",
  "Annie Hall (Movie)",
  "Apocalypse Now (Movie)",
  "Avatar: The Last Airbender (Series)",
  "Back to the Future (Movie)",
  "Bates Motel (Series)",
  "Beowulf (Book)",
  "Big Little Lies (Book)",
  "Black Swan (Movie)",
  "Blade Runner 2049 (Movie)",
  "Blood Meridian (Book)",
  "Boardwalk Empire (Series)",
  "Bojack Horseman (Series)",
  "Bonfire of the Vanities (Book)",
  "Breakfast at Tiffany's (Book)",
  "Brick (Movie)",
  "Brideshead Revisited (Book)",
  "Brooklyn Nine-Nine (Series)",
  "Call Me By Your Name (Book)",
  "Casablanca (Movie)",
  "Catch Me If You Can (Movie)",
  "Cat's Cradle (Book)",
  "Children of Men (Movie)",
  "Chinatown (Movie)",
  "Citizen Kane (Movie)",
  "Coraline (Book)",
  "Daredevil (Series)",
  "Dead Poets Society (Movie)",
  "Dexter (Series)",
  "Dirk Gently's Holistic Detective Agency (Book)",
  "Dirty Dancing (Movie)",
  "Dr. Strangelove (Movie)",
  "Drive (Movie)",
  "E.T. the Extra-Terrestrial (Movie)",
  "Eternal Sunshine of the Spotless Mind (Movie)",
  "Fear and Loathing in Las Vegas (Book)",
  "Ferris Bueller's Day Off (Movie)",
  "Fight Club (Book)",
  "Forrest Gump (Movie)",
  "Freakonomics (Book)",
  "Friday Night Lights (Series)",
  "Gone with the Wind (Book)",
  "Good Will Hunting (Movie)",
  "Gotham (Series)",
  "Gran Torino (Movie)",
  "Gravity (Movie)",
  "Great British Bake Off, The (Series)",
  "Green Mile, The (Book)",
  "Guardians of the Galaxy (Movie)",
  "Hannibal (Series)",
  "Harry Potter and the Chamber of Secrets (Book)",
  "Heart-Shaped Box (Book)",
  "High Fidelity (Book)",
  "House, M.D. (Series)",
  "I, Robot (Book, Isaac Asimov)",
  "In Cold Blood (Book)",
  "Inglourious Basterds (Movie)",
  "Interstellar (Movie)",
  "Into the Wild (Book)",
  "It's Always Sunny in Philadelphia (Series)",
  "Jaws (Movie)",
  "Joker (Movie)",
  "Kafka on the Shore (Book)",
  "Kingdom Hearts (Video Game)",
  "Kitchen Confidential (Book)",
  "L.A. Confidential (Movie)",
  "La La Land (Movie)",
  "Les Liaisons Dangereuses (Book)",
  "Mad Max: Fury Road (Movie)",
  "Memento (Movie)",
  "Midnight in Paris (Movie)",
  "Mindhunter (Series)",
  "Moonrise Kingdom (Movie)",
  "Naked Lunch (Book)",

  "Parasite (Movie)",
  "The Shape of Water (Movie)",
  "Arrival (Movie)",
  "Birdman (Movie)",
  "The Grand Budapest Hotel (Movie)",
  "Room (Book)",
  "The Revenant (Movie)",
  "Whiplash (Movie)",
  "Gone with the Wind (Movie)",
  "The Social Network (Movie)",
  "The Great British Baking Show (Series)",
  "Peaky Blinders (Series)",
  "Orange is the New Black (Series)",
  "The Crown (Series)",
  "The Mandalorian (Series)",
  "The Witcher (Series)",
  "The Queen's Gambit (Series)",
  "Stranger in a Strange Land (Book)",
  "The Leftovers (Series)",
  "The Umbrella Academy (Series)",
  "Killing Eve (Series)",
  "The Marvelous Mrs. Maisel (Series)",
  "Chernobyl (Series)",
  "Dark (Series)",
  "The Haunting of Hill House (Series)",
  "Fleabag (Series)",
  "Russian Doll (Series)",
  "Succession (Series)",
  "One-Punch Man (Manga)",
  "The Promised Neverland (Manga)",
  "Vinland Saga (Manga)",
  "Your Name (Anime)",
  "Spirited Away (Anime)",
  "Howl's Moving Castle (Anime)",
  "My Neighbor Totoro (Anime)",
  "Princess Mononoke (Anime)",
  "Grave of the Fireflies (Anime)",
  "Akira (Manga)",
  "Nausicaä of the Valley of the Wind (Manga)",
  "Ghost in the Shell (Manga)",
  "The Wind Rises (Anime)",
  "The Girl Who Leapt Through Time (Anime)",
  "Wolf Children (Anime)",
  "A Silent Voice (Anime)",
  "Weathering with You (Anime)",
  "5 Centimeters per Second (Anime)",
  "Summer Wars (Anime)"
]
